/*
Script generated by Aqua Data Studio 4.5.2 on Jun-04-2014 01:03:53 AM
Database: reserva
Schema: < All Schema >
Objects: TABLE
*/
ALTER TABLE reserva
	DROP CONSTRAINT reserva_ibfk_1
GO
ALTER TABLE reserva
	DROP CONSTRAINT PRIMARY
GO
ALTER TABLE estabelecimento
	DROP CONSTRAINT PRIMARY
GO
DROP INDEX PRIMARY ON reserva
GO
DROP INDEX CNPJ_CPF ON reserva
GO
DROP INDEX PRIMARY ON estabelecimento
GO
DROP TABLE reserva
GO
DROP TABLE estabelecimento
GO

CREATE TABLE estabelecimento ( 
	CNPJ_CPF    	varchar(18) NOT NULL,
	RAZAO_SOCIAL	varchar(100) NULL,
	NOME        	varchar(100) NULL,
	LOGIN       	varchar(100) NULL,
	SENHA       	varchar(100) NULL,
	EMAIL       	varchar(150) NULL 
	)
GO
CREATE TABLE reserva ( 
	ID_RESERVA  	decimal(10,0) NOT NULL,
	COD_MESA    	varchar(20) NULL,
	DT_RESERVA  	date NULL,
	NOME_CLIENTE	varchar(150) NULL,
	CONTATO     	varchar(13) NULL,
	CNPJ_CPF    	varchar(18) NULL 
	)
GO

CREATE UNIQUE INDEX PRIMARY
	ON estabelecimento(CNPJ_CPF)
GO
CREATE UNIQUE INDEX PRIMARY
	ON reserva(ID_RESERVA)
GO
CREATE INDEX CNPJ_CPF
	ON reserva(CNPJ_CPF)
GO
ALTER TABLE estabelecimento
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (CNPJ_CPF)
GO
ALTER TABLE reserva
	ADD CONSTRAINT reserva_ibfk_1
	FOREIGN KEY(CNPJ_CPF)
	REFERENCES estabelecimento(CNPJ_CPF)
GO
ALTER TABLE reserva
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (ID_RESERVA)
GO
